apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-pred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-price-pred
  template:
    metadata:
      labels:
        app: flight-price-pred
    spec:
      containers:
      - name: flight-price-pred
        image: hritik55/flight-price-prediction
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8501
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 20
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: flight-price-pred
spec:
  selector:
    app: flight-price-pred
  ports:
  - name: http
    port: 8501
    targetPort: 8501
  type: ClusterIP