pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git "https://github.com/Hritikrai55/mlops_project.git"
            }
        }

        stage('Build') {
            steps {
                dir('flight_price') {
                    sh 'pip install -r requirements.txt'
                    sh 'pytest'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('flight_price') {
                    sh 'docker build -t hritik55/flight-price-prediction:latest .'
                }
            }
        }

        stage('Docker Push') {
            steps {
                dir('flight_price') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                        sh 'docker push hritik55/flight-price-prediction:latest'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('flight_price') {
                    sh 'kubectl apply -f deployment.yaml'
                    sh 'kubectl rollout status deployment/flight-price-pred'
                }
            }
        }
    }

    post {
        always {
            emailext body: 'Build failed', subject: 'Build failed', to: 'hritikrai55@gmail.com'
        }
    }
}
